site_name: Mkdocs for Intelligent Textbooks
repo_url: https://github.com/IrvingGSea/i-book-v1.git

nav:
  - Home: index.md
  - About: about.md #add to actual folder
  - List of Chapters:
    - Intro: chapters/index.md
    - Chapter 1: chapters/chapter-1/index.md
    - Chapter 2: chapters/chapter-2/index.md
    - Chapter 3: chapters/chapter-3/index.md
    - Chapter 4: chapters/chapter-4/index.md
    - Chapter 5: chapters/chapter-5/index.md
    - Chapter 6: chapters/chapter-6/index.md
    - Chapter 7: chapters/chapter-7/index.md
    - Chapter 8: chapters/chapter-8/index.md
  - Sims: 
      - Gallery: sims/index.md
      - Sine Wave: sims/sine-wave/index.md
      - Stack Visualizer: sims/stack-visualizer/index.md
  - Glossary: glossary.md
  - Table of Contents: toc.md
  - License: license.md
  - Course Description: course-description.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md

theme:
  name: material 
  analytics: # analytics should be moved if theme is custom or not material
    provider: google
    property: G-8GFPXHN0M6

plugins:
  - search
  - glightbox
  - git-revision-date
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex

extra_javascript:
  - assets/javascripts/copy-prompt.js

extra_css:
  - assets/stylesheets/custom.css
  - css/extra.css


