site_name: Mkdocs for Intelligent Textbooks
repo_url: https://github.com/IrvingGSea/i-book-v1.git

nav:
  - Home: index.md
  - About: about.md #add to actual folder
  - List of Chapters:
    - Intro: chapters/index.md
    - Chapter 1: chapters/chapter-1.md
    - Chapter 2: chapters/chapter-2.md
    - Chapter 3: chapters/chapter-3.md
  - Tutorial: #add everything below
    - Introduction: tutorial/index.md
    - Getting Started: tutorial/getting-started.md
    - Navigation: tutorial/navigation.md
    - Admonitions: tutorial/admonitions.md
    - Quizzes: tutorial/quizzes.md
    - Upper Alpha Lists: tutorial/upper-alpha-lists.md
    - Google Analytics: tutorial/google-analytics.md
  - Prompts:
      - Introduction: prompts/index.md
      - Feature Mapping: prompts/feature-mapping.md
      - Enumerate Concepts: prompts/enumerate-concepts.md
      - Generate Logo: prompts/generate-logo.md
  - Sims: sims/index.md
  - Glossary: glossary.md
  - Table of Contents: toc.md
  - License: license.md
  - Course Description: course-description.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md

theme:
  name: material

plugins:
  - search
  - glightbox
  - git-revision-date
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex


